language: cpp

os: linux

dist: bionic

cache:
  directories:
  - ${HOME}/PawPawBuilds/debs
  - ${HOME}/PawPawBuilds/downloads

jobs:
  include:
    # linux native build
    - os: linux
      compiler: gcc
      env:
        - TARGET="linux"
        - PLUGINS="artyfx"

    # linux with macOS cross-compilation
    - os: linux
      compiler: gcc
      env:
        - TARGET="macos-old"
        - PLUGINS="artyfx"

    # linux with win32 cross-compilation
    - os: linux
      compiler: gcc
      env:
        - TARGET="win32"
        - PLUGINS="artyfx"

    # linux with win64 cross-compilation
    - os: linux
      compiler: gcc
      env:
        - TARGET="win64"
        - PLUGINS="artyfx"

before_install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
  - bash ${TRAVIS_BUILD_DIR}/bootstrap.sh ${TARGET}
  - bash ${TRAVIS_BUILD_DIR}/build-plugin.sh ${TARGET} ${PLUGINS}

#notifications:
  #email: true
  #irc: "ircs://chat.freenode.net:7070/#kxstudio"
