language: cpp

os: linux

dist: bionic

cache:
  directories:
  - ${HOME}/PawPawBuilds/debs
  - ${HOME}/PawPawBuilds/downloads

jobs:
  include:
    ## linux native build
    #- os: linux
      #compiler: gcc
      #env:
        #- TARGET="linux"
        #- PLUGINS="abgate artyfx caps fomp mda"

    ## linux with macOS cross-compilation
    #- os: linux
      #compiler: gcc
      #env:
        #- TARGET="macos-old"
        #- PLUGINS="abgate artyfx caps fomp mda"

    # linux with win32 cross-compilation
    - os: linux
      compiler: gcc
      env:
        - TARGET="win32"
        - PLUGINS="abgate artyfx caps fomp mda"

    # linux with win64 cross-compilation
    - os: linux
      compiler: gcc
      env:
        - TARGET="win64"
        - PLUGINS="abgate artyfx caps fomp mda"

before_install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
  - bash env WINEARCH=${TARGET} wineboot -i
  #- bash ${TRAVIS_BUILD_DIR}/bootstrap.sh ${TARGET}
  #- bash ${TRAVIS_BUILD_DIR}/build-plugins.sh ${TARGET} ${PLUGINS}

#before_deploy:
  #- bash ${TRAVIS_BUILD_DIR}/pack-plugins.sh ${TARGET} ${PLUGINS}

#deploy:
  #provider: releases
  #api_key: "GITHUB OAUTH TOKEN"
  #file_glob: true
  #file: setup/inno/PawPaw-*.exe
  #skip_cleanup: true
  #on:
    #tags: true

#notifications:
  #email: true
  #irc: "ircs://chat.freenode.net:7070/#kxstudio"
