language: cpp

cache:
  directories:
    - ${HOME}/PawPawBuilds/debs
    - ${HOME}/PawPawBuilds/downloads

env:
  global:
    - PLUGINS_BASE="abgate artyfx caps die-plugins dpf-plugins fomp mda"
    - PLUGINS_CROSS="blop"
    - PLUGINS_DISTRHO="distrho-ports-arctican distrho-ports-dexed distrho-ports-drowaudio distrho-ports-klangfalter distrho-ports-luftikus distrho-ports-obxd distrho-ports-pitched-delay distrho-ports-refine distrho-ports-tal-plugins distrho-ports-temper distrho-ports-vex distrho-ports-wolpertinger"

jobs:
  include:
    # linux native build
    - name: "Linux native"
      os: linux
      compiler: gcc
      dist: bionic
      env:
        - TARGET="linux"
        - PLUGINS="${PLUGINS_BASE} ${PLUGINS_CROSS}"

    # linux with macOS cross-compilation
    - name: "macOS cross-compiled"
      os: linux
      compiler: gcc
      dist: bionic
      env:
        - TARGET="macos-old"
        - PLUGINS="${PLUGINS_BASE}"

    # linux with win32 cross-compilation
    - name: "win32 cross-compiled"
      os: linux
      compiler: gcc
      dist: bionic
      env:
        - TARGET="win32"
        - PLUGINS="${PLUGINS_BASE} ${PLUGINS_CROSS}"
      services:
        - xvfb

    # linux with win64 cross-compilation
    - name: "win64 cross-compiled"
      os: linux
      compiler: gcc
      dist: bionic
      env:
        - TARGET="win64"
        - PLUGINS="${PLUGINS_BASE} ${PLUGINS_CROSS}"
      services:
        - xvfb

    # macOS native intel build
    - name: "macOS native intel"
      os: osx
      osx_image: xcode9.4
      env:
        - TARGET="macos"
        - PLUGINS="${PLUGINS_BASE} ${PLUGINS_CROSS}"

    # macOS native universal build
    #- name: "macOS native universal"
      #os: osx
      #osx_image: xcode12u
      #env:
        #- TARGET="macos-universal"
        #- PLUGINS="${PLUGINS_BASE} ${PLUGINS_CROSS}"

before_install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
  - bash ${TRAVIS_BUILD_DIR}/bootstrap-plugins.sh ${TARGET}
  - bash ${TRAVIS_BUILD_DIR}/build-plugins.sh ${TARGET} ${PLUGINS}

before_deploy:
  - bash ${TRAVIS_BUILD_DIR}/pack-plugins.sh ${TARGET} ${PLUGINS}

deploy:
  provider: releases
  api_key:
    secure: "xKXvMWEvj92IsFINpGlYEJeidLRoTeLIwrWVO06UrNNVCPiWC9z64Xthx/0xqQEv+2PA5GLkh9lnTm7aqQKbMNiVj4sQCcg3sVXEhkGkr27KNjHuQiFao+IeotU6bVTObzGhNR+US3LkRK9RSSvnmDBSUQB16+YgG6PZyXH7mQfoLycQQ8z24hLc4P2gGXbgd23viqZVxBh15HBm8jSm0q5Y5JZ2D/ETQWIijv+Cd7f3Q4j989Q4ZULiDyPs6gMR6Klr85Z8iNXEZRCw/dJ800IrWV9tetJFZFVOG2nWATPSFD9L1DLlJtD0tPJjk/n7DpUEivdrrLgm2C1MaTfDWQU7OOktkcNv6oUB++hWqD/d9bj1teSu9lrUkAS4QPWGWgsMQH/eWquoS6vQOE7ERAHTDgbsS1aPxnuWyG2lyefbSEJCXBOpbcWLAfAr3cdkS+QhFHZzKvZLwJZFkKR0FEKKPkt+CViLmtSbeM7uFRhX3B4uA9EByZonlvupgKfyt/WKoqpsb1hF16tVrZOmTFf2/btLOw8PUD1opAx0aXjH+XcWH6y93wsP41E3VMO/gc8jc7npa+JsMDXaHFf/DMQvj9rVF8deHoshx8Sl3n0RpEhMyV+lXKKfewryqnfWNGak7wNQQhFr4Xqv6mleBFAX1Miy12KkzYxltfwi53o="
  file_glob: true
  file:
    - setup/inno/PawPaw-*.exe
    - setup/macos/PawPaw-*.pkg
    #- setup/macos-universal/PawPaw-*.pkg
  skip_cleanup: true
  on:
    all_branches: true

#notifications:
  #email: true
  #irc: "ircs://chat.freenode.net:7070/#kxstudio"
